### ISSUE TITLE
path to foundation.min.js got lost

### ISSUE THREAD

**Issue by jkkoenig** [cbrunet/typo3-cb_foundation#7]
![cb-foundation](https://cloud.githubusercontent.com/assets/8867959/8004292/e745ade6-0b7e-11e5-8504-4703433abe19.JPG)

in an installation of cb_foundation the mobile menu did not work any more. a colleague fixed the issue. He put the file foundation.min.js in the root folder in js/foundation.min.js and ist worked again. 

so i asked myself why does Typo3 do not use the file in typo3conf/ext/... and I found out the typoscript setup for the Foundation JavaScript initialization is missing. See screenshot. What can I do to fix this?

Thanks, Jürgen

**Comment by cbrunet** [comment]
Dear Jürgen,

Is the static template loaded? <code>page.jsFooterInline.65</code> should contain the code that calls foundation javascript initialization. Furthermore, the is a constant (which is set by default) to specify if you want to load the js lib. The lib is load by <code>page.includeJSFooter.foundation</code> . From you screenshot, my guess is that you did not include the static template.

**Comment by jkkoenig** [comment]
Oh that's easy...right somehow the static template got lost....now it is included and it works again. Thanks!!!

There is another issue we somehow solved with some extra javascript. You can see it now on http://www.value-and-equivalence.de/ The second level of the mobiel menu does not open on click.

We solved it with somm etxtra javascript:
 $(document).ready(function(){

  
    $('li.has-submenu.off-canvas a').click(function(){
     //alert('asdfas');  
     $(this).parent().next('.left-submenu').show();
   });

$('.left-submenu.off-canvas li.back a').click(function(){
  //alert('asdfas');  
  $(this).parent().parent().hide();
});
  });

 )
}

This is not exactly the functionality of foundation. Do you have an idea why this occurs?

Thanks
Jürgen

**Comment by cbrunet** [comment]
I think you are missing some &lt;li&gt; tags around &lt;ul&gt; tags for submenus. Compare carefully with the example in documentation.

**Comment by jkkoenig** [comment]
ok thanks, I will check that! Have a nice weekend!
